language: php

php:
  - 7.2.11

sudo: required

services:
  - mysql

install:
  - travis_retry composer install --no-interaction --no-suggest
  - composer show --installed

before_script:
  - travis_retry composer self-update

script:
  - composer make-db-test
  - composer test

before_install:
  - openssl aes-256-cbc -K $encrypted_bea0181439c1_key -iv $encrypted_bea0181439c1_iv -in git_deploy_key.enc -out /tmp/git_deploy_key -d
  - chmod 600 /tmp/git_deploy_key
  - echo 'echo ${SSH_PASSPHRASE}' > /tmp/askpass && chmod +x /tmp/askpass
  - eval "$(ssh-agent -s)"
  - DISPLAY=":0.0" SSH_ASKPASS="/tmp/askpass" setsid ssh-add /tmp/git_deploy_key </dev/null

